from . import views
from django.urls import path


urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home1'),
    path('about/', views.about, name='about'),
    path('businesses/', views.business_index, name='index'),
    path('businesses/<int:business_id>/',
         views.business_detail, name='business_detail'),
    path('businesses/<int:business_id>/add_business_review/',
         views.add_business_review, name='add_business_review'),
    path('businesses/create/', views.BusinessCreate.as_view(),
         name='business_create'),
    path('businesses/<int:pk>/update/',
         views.BusinessUpdate.as_view(), name='business_update'),
    path('businesses/<int:pk>/delete/',
         views.BusinessDelete.as_view(), name='business_delete'),
    path('groupclasses/', views.groupclass_index, name='class_index'),
    path('groupclasses/<int:groupclass_id>/',
         views.groupclass_detail, name='class_detail'),
    path('groupclasses/<int:groupclass_id>/add_groupclass_review/',
         views.add_groupclass_review, name='add_groupclass_review'),
    path('groupclasses/create', views.GroupClassCreate.as_view(), name='class_create'),
    path('groupclasses/<int:pk>/update/',
         views.GroupClassUpdate.as_view(), name='class_update'),
    path('groupclasses/<int:pk>/delete/',
         views.GroupClassDelete.as_view(), name='class_delete'),
    path('coaches/', views.coach_index, name='coach_index'),
    path('coaches/<int:coach_id>/', views.coach_detail, name='coach_detail'),
    path('coaches/<int:coach_id>/add_coach_review/',
         views.add_coach_review, name='add_coach_review'),
    path('coaches/create', views.CoachCreate.as_view(), name='coach_create'),
    path('coaches/<int:pk>/update/',
         views.CoachUpdate.as_view(), name='coach_update'),
    path('coaches/<int:pk>/delete/',
         views.CoachDelete.as_view(), name='coach_delete'),
    path('profile/', views.profile, name='profile'),
    path('profile/upgrade', views.upgrade_profile, name='upgrade_profile'),
    path('profile/downgrade', views.downgrade_profile, name='downgrade_profile'),
    path('accounts/signup/', views.signup, name='signup'),
    path('search/', views.SearchResultsView.as_view(), name= 'search_results'),
    path('profile/<int:pk>/update', views.ProfileUpdate.as_view(), name= 'profile_update'),
    path('profile/<int:pk>/delete', views.ProfileDelete.as_view(), name= 'profile_delete'),

]
