# Generated by Django 4.1.4 on 2023-01-05 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter the name of your business / establishment', max_length=100)),
                ('email', models.CharField(help_text='e.g. example@email.com', max_length=100)),
                ('location', models.PositiveIntegerField(help_text='Please enter your 5 digit zip or postal code', verbose_name='Zip Code')),
                ('business_type', models.CharField(choices=[('Yoga', 'Yoga'), ('Gym', 'Gym'), ('Chiropractor', 'Chiropractor'), ('Resturant', 'Resturant'), ('Shop', 'Shop'), ('Acupuncture', 'Acupuncture'), ('Massage', 'Massage')], default='Yoga', max_length=100)),
                ('business_hours', models.CharField(choices=[('24 hours a day', '24 hours a day'), ('Hours to be determined', 'Hours to be determined'), ('Contact business for more information', 'Contact business for more information'), ('8am - 5pm', '8am - 5pm'), ('8am - 10pm', '8am - 10pm'), ('6am - 10pm', '6am - 10pm'), ('12pm - 12am', '12pm - 12am'), ('9am - 6pm', '9am - 6pm'), ('Closed for the Holidays', 'Closed for the Holidays')], default='24 hours a day', max_length=100)),
                ('rates', models.TextField(help_text='Please add the rates and prices of the services / goods you offer', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter your name here', max_length=100)),
                ('email', models.CharField(help_text='e.g. example@email.com', max_length=100)),
                ('location', models.PositiveIntegerField(help_text='Please enter your 5 digit zip or postal code', verbose_name='Zip Code')),
                ('specialty', models.CharField(help_text='Please enter your specialty / area of expertise here', max_length=100)),
                ('bio', models.TextField(help_text='Please add additional information about your qualifications and program', max_length=250)),
                ('availability', models.TextField(help_text='Please add information regarding your availability', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter the name of your group class / activity', max_length=100)),
                ('date', models.DateField(help_text='Please select the date the event will take place', verbose_name='Group Class Date')),
                ('description', models.TextField(help_text='Please add any additional information regarding the event', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GroupClassReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=1)),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Date')),
                ('groupclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.groupclass')),
            ],
        ),
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=1)),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coach')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=1)),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.business')),
            ],
        ),
    ]
