# Generated by Django 4.1.4 on 2023-01-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessreview',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='coachreview',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='groupclassreview',
            options={'ordering': ['-date']},
        ),
    ]
