# Generated by Django 4.1.4 on 2022-12-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('Y', 'Yoga'), ('G', 'Gym'), ('C', 'Chiropractor'), ('R', 'Resturant'), ('S', 'Shop'), ('A', 'Acupuncture'), ('M', 'Massage')], default='Y', max_length=1),
        ),
    ]
