# Generated by Django 4.1.4 on 2023-01-03 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='groupclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.groupclass'),
        ),
    ]
