# Generated by Django 4.1.4 on 2022-12-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('coach_specialty', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=250)),
                ('availability', models.TextField(max_length=250)),
            ],
        ),
    ]
