# Generated by Django 4.1.4 on 2022-12-29 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='coach_specialty',
            new_name='specialty',
        ),
    ]
