# Generated by Django 4.1.4 on 2023-01-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_review_groupclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Gym', 'Gym'), ('Chiropractor', 'Chiropractor'), ('Resturant', 'Resturant'), ('Shop', 'Shop'), ('Acupuncture', 'Acupuncture'), ('Massage', 'Massage')], default='Yoga', max_length=100),
        ),
    ]
