# Generated by Django 4.1.4 on 2022-12-29 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_business_business_type'),
        ('main_app', '0002_coach'),
    ]

    operations = [
    ]
