# Generated by Django 4.1.4 on 2022-12-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_0002_alter_business_business_type_0002_coach'),
        ('main_app', '0003_rename_coach_specialty_coach_specialty'),
    ]

    operations = [
    ]
