# Generated by Django 4.1.4 on 2023-01-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_business_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_hours',
            field=models.CharField(choices=[('24 hours a day', '24 hours a day'), ('Hours to be determined', 'Hours to be determined'), ('Contact business for more information', 'Contact business for more information'), ('8am - 5pm', '8am - 5pm'), ('8am - 10pm', '8am - 10pm'), ('6am - 10pm', '6am - 10pm'), ('12pm - 12am', '12pm - 12am'), ('9am - 6pm', '9am - 6pm'), ('Closed for the Holidays', 'Closed for the Holidays')], default='24 hours a day', max_length=100),
        ),
    ]
