# Generated by Django 4.1.4 on 2023-01-04 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=1)),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Date')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coach')),
            ],
        ),
    ]
