# Generated by Django 4.1.4 on 2023-01-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_business_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.CharField(help_text='e.g. example@email.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.PositiveIntegerField(help_text='Please enter your 5 digit zip or postal code', max_length=5, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(help_text='Please enter the name of your business / establishment', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='rates',
            field=models.TextField(help_text='Please add the rates and prices of the services / goods you offer', max_length=500),
        ),
        migrations.AlterField(
            model_name='coach',
            name='availability',
            field=models.TextField(help_text='Please add information regarding your availability', max_length=250),
        ),
        migrations.AlterField(
            model_name='coach',
            name='bio',
            field=models.TextField(help_text='Please add additional information about your qualifications and program', max_length=250),
        ),
        migrations.AlterField(
            model_name='coach',
            name='email',
            field=models.CharField(help_text='e.g. example@email.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='location',
            field=models.PositiveIntegerField(help_text='Please enter your 5 digit zip or postal code', max_length=5, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(help_text='Please enter your name here', max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='specialty',
            field=models.CharField(help_text='Please enter your specialty / area of expertise here', max_length=100),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='date',
            field=models.DateField(help_text='Please select the date the event will take place', verbose_name='Group Class Date'),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='description',
            field=models.TextField(help_text='Please add any additional information regarding the event', max_length=500),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='name',
            field=models.CharField(help_text='Please enter the name of your group class / activity', max_length=100),
        ),
    ]
