# Generated by Django 4.1.4 on 2023-01-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_business_email_alter_business_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.PositiveIntegerField(help_text='Please enter your 5 digit zip or postal code', verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='location',
            field=models.PositiveIntegerField(help_text='Please enter your 5 digit zip or postal code', verbose_name='Zip Code'),
        ),
    ]
