# Generated by Django 4.1.4 on 2023-01-04 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_coachreview_date_businessreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreview',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='coachreview',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
